-- ============================================================
-- GovHub Tanzania — demo seed data
-- Run AFTER schema.sql. Mirrors the sample data used in the
-- HTML prototype so the real app and the prototype match.
-- ============================================================

insert into agencies (code, name, description, accent_color, phone, email, address) values
  ('TRA', 'Tanzania Revenue Authority', 'Collects national tax revenue and administers taxpayer registration, VAT, and customs.', '#0B6E4F', '+255 22 219 9000', 'info@tra.go.tz', 'TRA House, Dar es Salaam'),
  ('BRELA', 'Business Registrations & Licensing Agency', 'Registers companies, business names, and handles annual statutory filings.', '#0A4D68', '+255 22 218 4508', 'info@brela.go.tz', 'Kivukoni, Dar es Salaam'),
  ('NIDA', 'National Identification Authority', 'Issues the National Identity Card and manages corrections to registered ID data.', '#B9860C', '+255 22 286 4501', 'info@nida.go.tz', 'Kijitonyama, Dar es Salaam'),
  ('IMM', 'Immigration Services Department', 'Processes passports, visas, and residence permits for citizens and foreign nationals.', '#0B6E4F', '+255 22 285 0575', 'info@immigration.go.tz', 'Ghana Avenue, Dar es Salaam'),
  ('RITA', 'Registration, Insolvency & Trusteeship Agency', 'Registers births, deaths, marriages, and manages trusteeship services.', '#8A4B08', '+255 22 286 3475', 'info@rita.go.tz', 'Upanga, Dar es Salaam'),
  ('OSHA', 'Occupational Safety & Health Authority', 'Regulates workplace safety and mandatory employer registration.', '#0A4D68', '+255 22 286 3072', 'info@osha.go.tz', 'Dar es Salaam'),
  ('NEMC', 'National Environment Management Council', 'Issues environmental impact and pollution permits for regulated activities.', '#0B6E4F', '+255 22 277 4852', 'info@nemc.or.tz', 'Regent Estate, Dar es Salaam'),
  ('TMDA', 'Tanzania Medicines & Medical Devices Authority', 'Registers medicines, medical devices, and regulated health products.', '#B94A1F', '+255 22 245 0512', 'info@tmda.go.tz', 'Mabibo, Dar es Salaam'),
  ('MoL', 'Ministry of Lands, Housing & Human Settlements', 'Handles land transfers, title deeds, and land survey applications.', '#8A4B08', '+255 22 212 1145', 'info@ardhi.go.tz', 'Kivukoni Front, Dodoma'),
  ('LGA', 'Local Government Authorities', 'Issues local business licenses and municipal permits.', '#0A4D68', 'Varies by council', null, 'Regional & District Offices'),
  ('NSSF', 'National Social Security Fund', 'Manages employer and employee social security contributions.', '#0B6E4F', '+255 22 218 2857', 'info@nssf.or.tz', 'Dar es Salaam'),
  ('NHIF', 'National Health Insurance Fund', 'Administers member registration for national health cover.', '#B9860C', '+255 22 291 0575', 'info@nhif.or.tz', 'Dar es Salaam'),
  ('TANESCO', 'Tanzania Electric Supply Company', 'Processes new electricity connection applications.', '#B94A1F', '+255 22 245 1136', 'info@tanesco.co.tz', 'Ubungo, Dar es Salaam')
on conflict (code) do nothing;

-- Forms — status is 'published' so they show up on the public site immediately.
insert into forms (agency_id, category_id, title, slug, description, purpose, eligibility, requirements, processing_time, fee, submission_office, version, reference_code, status, last_updated)
select a.id, c.id, v.title, v.slug, v.description, v.purpose, v.eligibility, v.requirements, v.processing_time, v.fee, v.submission_office, v.version, v.reference_code, 'published', v.last_updated
from (values
  ('TRA','Tax','TIN Registration','tin-registration','Register for a Tax Identification Number required for all formal tax obligations in Tanzania.','A TIN is required to open a business bank account, register for VAT, and file any tax return with TRA.','Any individual or registered business operating in Tanzania.', array['National ID (NIDA number)','Passport-size photo','Proof of address'], '1–3 business days','Free','Online via TRA portal or any TRA office','v2.1','TRA-TIN-001', timestamptz '2026-06-02'),
  ('TRA','Tax','VAT Registration','vat-registration','Register a business for Value Added Tax once turnover thresholds are met.','Required before a business can charge or reclaim VAT on taxable supplies.','Businesses with turnover above the statutory VAT threshold, or voluntary registrants.', array['Valid TIN','Certificate of Incorporation (if a company)','Business bank account details'], '3–5 business days','Free','Online via TRA portal','v1.4','TRA-VAT-002', timestamptz '2026-03-11'),
  ('TRA','Tax','Tax Clearance Certificate','tax-clearance','An official certificate confirming a taxpayer has no outstanding tax liabilities.','Often required for tender applications, loan approvals, and vehicle transfers.','Taxpayers in good standing with no outstanding returns.', array['TIN','Latest filed tax return'], '5 business days','TZS 10,000','TRA office or online request','v1.0','TRA-TCC-003', timestamptz '2026-01-20'),
  ('BRELA','Business','Company Registration','company-registration','Register a new limited company with BRELA.','Formally establishes a company as a legal entity able to trade, borrow, and be taxed.','Any founder(s) forming a new company in Tanzania.', array['Reserved company name','Memorandum & Articles of Association','Director & shareholder ID copies'], '5–7 business days','TZS 250,000 (varies by capital)','Online via BRELA portal','v3.0','BRELA-CR-010', timestamptz '2026-05-28'),
  ('BRELA','Business','Business Name Registration','business-name','Register a sole proprietorship or trading name.','Required to legally trade under a business name distinct from the owner''s personal name.','Sole proprietors and partnerships.', array['National ID','Proposed business name'], '2–3 business days','TZS 20,000','Online via BRELA portal','v1.6','BRELA-BN-011', timestamptz '2025-11-14'),
  ('BRELA','Business','Annual Returns Filing','annual-returns','Mandatory yearly filing to keep a company''s registration active.','Confirms company details are current and avoids penalties or deregistration.','All registered companies, annually.', array['Company registration number','Updated director/shareholder details'], '3 business days','TZS 50,000','Online via BRELA portal','v1.2','BRELA-AR-012', timestamptz '2026-02-09'),
  ('NIDA','Identity','National ID Application','national-id','Apply for the Tanzanian National Identity Card.','The National ID is required for banking, SIM registration, voting, and most government services.','Citizens and eligible residents aged 18 and above.', array['Birth certificate','Two passport photos','Proof of residence'], '14–30 business days','Free (first issue)','NIDA registration centre','v2.0','NIDA-ID-020', timestamptz '2026-04-17'),
  ('NIDA','Identity','ID Data Correction','id-correction','Correct an error in your registered National ID information.','Fixes spelling, date of birth, or biometric mismatches on an issued ID.','Existing National ID holders.', array['Current National ID','Supporting evidence of correct details'], '10 business days','TZS 5,000','NIDA registration centre','v1.1','NIDA-ID-021', timestamptz '2025-09-30'),
  ('IMM','Immigration','Passport Application','passport-application','Apply for a new ordinary Tanzanian passport.','Required for international travel.','Tanzanian citizens of any age (minors require guardian consent).', array['National ID or birth certificate','Two passport photos','Proof of address'], '7–10 business days','TZS 150,000','Immigration office (appointment required)','v2.3','IMM-PSP-030', timestamptz '2026-06-30'),
  ('IMM','Immigration','Visa Application','visa-application','Apply for an entry visa to Tanzania for a foreign national.','Grants legal permission to enter and stay in Tanzania for a defined period.','Foreign nationals not covered by visa-exemption agreements.', array['Valid passport (6+ months)','Passport photo','Proof of onward travel'], '3–5 business days (or on arrival)','USD 50–100','Online e-Visa portal or on arrival','v1.5','IMM-VSA-031', timestamptz '2026-01-08'),
  ('RITA','Identity','Birth Certificate','birth-certificate','Apply for an official birth certificate or a certified copy.','Foundational identity document required for school enrolment, ID, and passport applications.','Parents/guardians of the registered child, or the individual once of age.', array['Notification of birth from health facility','Parents'' National ID'], '3–5 business days','TZS 3,500','RITA office or district registrar','v1.3','RITA-BC-040', timestamptz '2025-12-19'),
  ('RITA','Identity','Death Certificate','death-certificate','Register a death and obtain an official death certificate.','Required for estate settlement, insurance claims, and closing official records.','Next of kin or authorised representative.', array['Medical cause-of-death report','Deceased''s National ID (if available)'], '3–5 business days','TZS 3,500','RITA office or district registrar','v1.1','RITA-DC-041', timestamptz '2025-10-02'),
  ('OSHA','Business','Workplace Registration','workplace-registration','Register a new workplace for occupational safety compliance.','Legally required before a workplace with employees can begin operating.','Employers establishing a new workplace.', array['Business registration certificate','Site layout plan'], '5 business days','Based on workplace category','OSHA regional office','v1.0','OSHA-WR-050', timestamptz '2025-08-22'),
  ('NEMC','Environment','Environmental Permit','environmental-permit','Obtain approval for activities requiring an environmental impact assessment.','Required before construction or industrial activity with environmental impact can proceed.','Project developers in regulated sectors.', array['Environmental Impact Statement','Project description'], '30–60 business days','Based on project scale','NEMC head office','v1.2','NEMC-EP-060', timestamptz '2026-02-27'),
  ('TMDA','Health','Medicine Registration','drug-registration','Register a medicine or medical device for legal sale in Tanzania.','Required before any pharmaceutical product can be marketed or distributed.','Licensed manufacturers or authorised local agents.', array['Product dossier','Certificate of Pharmaceutical Product'], '90–180 business days','Based on product category','TMDA head office','v2.0','TMDA-MR-070', timestamptz '2026-05-05'),
  ('MoL','Lands','Land Transfer','land-transfer','Transfer registered land or a title deed between parties.','Legally records a change of ownership of registered land.','Current title holder and incoming buyer/recipient.', array['Original title deed','Sale agreement','Land rent clearance'], '14–21 business days','Based on land value','Ministry of Lands zonal office','v1.4','MOL-LT-080', timestamptz '2026-03-30'),
  ('LGA','Business','Business License Application','business-license','Apply for a local business license from your municipal or district council.','Legally required to operate a business premises within a local authority area.','Registered business owners operating within the council''s jurisdiction.', array['Business registration certificate','TIN certificate','Premises lease agreement'], '5–7 business days','Varies by council and business category','District/municipal council office','v1.0','LGA-BL-090', timestamptz '2025-07-15'),
  ('NSSF','Business','Employer Registration','nssf-employer','Register an employer for mandatory social security contributions.','Required before an employer can enrol staff in the National Social Security Fund.','Any registered business with employees.', array['Business registration certificate','TIN'], '3 business days','Free','NSSF regional office','v1.0','NSSF-ER-100', timestamptz '2025-12-01'),
  ('NHIF','Health','Member Registration','nhif-member','Register as an individual or employer scheme member of the National Health Insurance Fund.','Provides access to subsidised healthcare at accredited facilities.','Employed individuals, self-employed, and voluntary members.', array['National ID','Passport photo'], '1–2 business days','Based on contribution band','NHIF office or employer HR','v1.1','NHIF-MR-110', timestamptz '2026-01-30'),
  ('TANESCO','Business','New Electricity Connection','tanesco-connection','Apply for a new electricity connection to a premises.','Required to legally connect a new or unconnected property to the national grid.','Property owner or authorised tenant with proof of premises.', array['Proof of land/premises ownership or tenancy','National ID'], '10–20 business days','Based on connection distance','TANESCO regional office','v1.3','TANESCO-NC-120', timestamptz '2026-04-04')
) as v(agc, cat, title, slug, description, purpose, eligibility, requirements, processing_time, fee, submission_office, version, reference_code, last_updated)
join agencies a on a.code = v.agc
join categories c on c.name = v.cat
on conflict (slug) do nothing;
